### ISSUE TITLE
error importing package

### ISSUE THREAD

**Issue by KalebKloppe** [m5kr1pka/canvas-scroll-clip#26]
I have tried both import methods
```jsx
import CanvasScrollClip from 'canvas-scroll-clip';
```
```
const CanvasScrollClip = require('canvas-scroll-clip').default
```
They result in the same error
```sh
/home/kaleb/code/ttf-cms/node_modules/canvas-scroll-clip/dist/esbuild/main.esm.js:393
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.newLoader [as .js] (/home/kaleb/code/ttf-cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kaleb/code/ttf-cms/components/Media/index.tsx:15:62)

Node.js v18.14.0
```

This is the project I am using:
https://github.com/KalebKloppe/nextjs-custom-server

**Comment by Gabrielfcs** [comment]
You are trying to use it without considering it a client-side component. Use `'use client';` on top of the files that are using it and then it will work.

**Comment by KalebKloppe** [comment]
> You are trying to use it without considering it a client-side component. Use `'use client';` on top of the files that are using it and then it will work.

I was using the legacy pages router, not the App router. No "use client"

**Comment by m5kr1pka** [comment]
@KalebKloppe did you managed to solve this?
